### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by hkurra** [dbleicher/recyclerview-grid-quickreturn#3]
I try to build this library on my machine but the project that i checkout has lots of structure problem i mean android studio throwing lots of error or i am doing someting wrong so please provide some info on how to build or use this library and  its better to have gradle dependency

**Comment by dbleicher** [comment]
Hi @hkurra the code in this repo is not a library, it is an example application that demonstrates how to implement the QR pattern on a recyclerview with a grid layoutmanager.  Please see the README and the code itself for usage.

**Comment by hkurra** [comment]
sorry my bad but still I am not able to compile the project as it has many structure problem .
